# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Word.create(spell: 'ant')
Word.create(spell: 'bag')
Word.create(spell: 'bed')
Word.create(spell: 'cat')
Word.create(spell: 'cap')
Word.create(spell: 'dog')
Word.create(spell: 'egg')
Word.create(spell: 'fog')
Word.create(spell: 'food')
Word.create(spell: 'god')
Word.create(spell: 'hat')
Word.create(spell: 'hit')
Word.create(spell: 'ill')
Word.create(spell: 'job')
Word.create(spell: 'king')
Word.create(spell: 'lab')
Word.create(spell: 'lady')
Word.create(spell: 'man')
Word.create(spell: 'mad')
Word.create(spell: 'nap')
Word.create(spell: 'nod')
Word.create(spell: 'oar')
Word.create(spell: 'pen')
Word.create(spell: 'pet')
Word.create(spell: 'pig')
Word.create(spell: 'quad')
Word.create(spell: 'rat')
Word.create(spell: 'sit')
Word.create(spell: 'son')
Word.create(spell: 'tab')
Word.create(spell: 'toe')
Word.create(spell: 'use')
Word.create(spell: 'verb')
Word.create(spell: 'wag')
Word.create(spell: 'wait')
Word.create(spell: 'xi')
Word.create(spell: 'yes')
Word.create(spell: 'zoo')
